# platform :ios, '9.0'

target 'wassup' do
  use_frameworks!

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

# Facebook
pod 'FBSDKLoginKit'

# Google
pod 'GoogleSignIn'

# Others
pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

end
